version: "3.9"
services:
  backend:
    build: ./fridge_manager
    ports:
      - "8000:8000"

  frontend:
    image: nginx
    volumes:
      - ./assets:/usr/share/nginx/html:ro
    ports:
      - "80:80"

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
